name: Despliegue a Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        
      - name: Instalar dependencias y Construir
        run: |
          npm install
          npm run build
          
      - name: Dynamic Cache Busting
        run: echo "Deploy ID ${{ github.run_id }} - Commit ${{ github.sha }}" > dist/deploy-id.txt

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Deploy to Firebase Hosting
        run: npx firebase-tools@13.7.0 deploy --only hosting --project pieldivina-8e167 --non-interactive
