name: Despliegue a Firebase
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar código
        uses: actions/checkout@v4
        
      - name: Instalar dependencias y Construir
        run: |
          npm install
          npm run build
          
      - name: Autenticar y Desplegar a Firebase
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/firebase-service-account.json
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: |
          echo "Longitud del secreto FIREBASE_SERVICE_ACCOUNT: ${#FIREBASE_SERVICE_ACCOUNT}"
          echo "$FIREBASE_SERVICE_ACCOUNT" > $GOOGLE_APPLICATION_CREDENTIALS
          echo "Tamaño del archivo generado:"
          ls -l $GOOGLE_APPLICATION_CREDENTIALS
          echo "Validando JSON (si es válido no mostrará error, si es inválido fallará):"
          jq empty $GOOGLE_APPLICATION_CREDENTIALS || echo "El archivo no es un JSON válido"
          npx firebase-tools@15.22.1 deploy --only hosting
